// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Embedded Pure source files.
//!
//! [`legend_pure_build`] (used by this crate's `build.rs`) reads
//! `[[package.metadata.legend-pure.repos]]` from `Cargo.toml`,
//! deserializes each Java descriptor JSON, and emits one
//! `REPO_<NAME>_FILES` array + `REPO_<NAME>_META` constant per repo —
//! plus a `default_embedded_repos()` function used by
//! [`crate::repo::Repo::default_embedded`].
//!
//! Consumers should always go through [`crate::repo::Repo`]. The raw
//! [`PureSourceFile`] type is exposed only because the generated
//! constants reference it.

/// A single embedded Pure source file with its canonical URL.
#[derive(Debug)]
pub struct PureSourceFile {
    /// Canonical URL of the form `/{repo_name}/{rel_path}` — matches
    /// the form used by `SourceInformation.source` everywhere else.
    pub path: &'static str,
    /// File contents.
    pub content: &'static str,
}

// Generated by `legend-pure-build`. Defines, per repo:
//   - `REPO_<NAME>_META: crate::repo::RepoMeta`
//   - `REPO_<NAME>_FILES: &[crate::sources::PureSourceFile]`
//     (mixed .pure + .json)
// Plus the aggregator:
//   - `default_embedded_repos() -> Vec<crate::repo::Repo>`
include!(concat!(env!("OUT_DIR"), "/legend_pure_repos.rs"));
