// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Emits one Java `enum` per reachable Pure `Enumeration`. The enum
//! constants follow the Pure declaration order. A static `fromPure(String)`
//! lookup maps the Pure-side member name to the Java constant.

use std::path::PathBuf;

use legend_pure_parser_pure::ids::ElementId;
use legend_pure_parser_pure::model::{Element, PureModel};

use crate::model::{CodegenError, JavaFile, Options};
use crate::naming::{
    join_java_package, pure_fqn_segments, pure_package_segments_of, safe_java_identifier,
};

pub(crate) fn emit_enum(
    model: &PureModel,
    enum_id: ElementId,
    opts: &Options,
) -> Result<JavaFile, CodegenError> {
    let segments = pure_fqn_segments(model, enum_id);
    let leaf = segments
        .last()
        .map(smol_str::SmolStr::as_str)
        .unwrap_or("Enum");
    let java_simple = safe_java_identifier(leaf);
    let pkg_segments = pure_package_segments_of(model, enum_id);
    let java_package = join_java_package(&opts.java_root_package, &pkg_segments);

    let enumeration = match model.get_element(enum_id) {
        Element::Enumeration(e) => e,
        _ => unreachable!("emit_enum called on non-Enumeration element"),
    };

    let mut body = String::new();
    body.push_str("// Generated by legend-pure-java-codegen — do not edit by hand.\n");
    body.push_str(&format!("package {java_package};\n\n"));
    body.push_str(&format!("public enum {java_simple} {{\n"));

    let mut consts: Vec<(String, String)> = Vec::with_capacity(enumeration.values.len());
    for (i, value) in enumeration.values.iter().enumerate() {
        let java_const = enum_constant_name(value.name.as_str());
        if i > 0 {
            body.push_str(",\n");
        }
        body.push_str(&format!(
            "    {java_const}(\"{}\")",
            escape_java_string(value.name.as_str())
        ));
        consts.push((java_const, value.name.to_string()));
    }
    body.push_str(";\n\n");

    body.push_str("    private final String pureName;\n\n");
    body.push_str(&format!(
        "    {java_simple}(String pureName) {{ this.pureName = pureName; }}\n\n"
    ));
    body.push_str("    public String pureName() { return pureName; }\n\n");
    body.push_str(&format!(
        "    public static {java_simple} fromPure(String pureName) {{\n"
    ));
    body.push_str(&format!("        for ({java_simple} v : values()) {{\n"));
    body.push_str("            if (v.pureName.equals(pureName)) return v;\n");
    body.push_str("        }\n");
    body.push_str(&format!(
        "        throw new IllegalArgumentException(\"Unknown {java_simple} member: \" + pureName);\n"
    ));
    body.push_str("    }\n");

    body.push_str("}\n");

    let mut path = PathBuf::new();
    for seg in java_package.split('.') {
        path.push(seg);
    }
    path.push(format!("{java_simple}.java"));

    Ok(JavaFile {
        relative_path: path,
        contents: body,
    })
}

fn enum_constant_name(pure_name: &str) -> String {
    // Java enum constants must be valid identifiers; uppercase by
    // convention. Pure enum members are typically already SCREAMING_CASE
    // or camelCase — preserve case but escape unsafe characters.
    safe_java_identifier(pure_name)
}

fn escape_java_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}
