// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Emits the single static-functions facade class.
//!
//! Layout:
//! ```ignore
//! package <root>;
//! public final class PureFunctions {
//!     private PureFunctions() {}
//!     public static <RetJava> <pkg_pureFqn>(<args>, PureRustEvaluator eval) {
//!         return PureProxyFactory.<wrapMethod>(
//!             eval.evaluate("<mangled FQN>", <unwrapped args>),
//!             <returnTypeToken>, eval);
//!     }
//! }
//! ```

use std::path::PathBuf;

use legend_pure_parser_pure::ids::ElementId;
use legend_pure_parser_pure::model::{Element, PureModel};

use crate::closure::ReachableSet;
use crate::model::{CodegenError, JavaFile, Options, ResolvedFn};
use crate::naming::{
    java_static_method_name, join_java_package, pure_fqn_segments, pure_package_segments_of,
    safe_java_identifier,
};
use crate::types::{JavaType, TypePosition, render_java_type};

pub(crate) fn emit_functions_class(
    model: &PureModel,
    fns: &[ResolvedFn],
    reachable: &ReachableSet,
    opts: &Options,
) -> Result<JavaFile, CodegenError> {
    let mut body = String::new();
    body.push_str("// Generated by legend-pure-java-codegen — do not edit by hand.\n");
    body.push_str(&format!("package {};\n\n", opts.java_root_package));
    body.push_str("import org.finos.legend.pure.rust.PureRustEvaluator;\n");
    body.push_str("import org.finos.legend.pure.rust.proxy.PureProxyFactory;\n\n");
    body.push_str(&format!(
        "public final class {} {{\n",
        opts.functions_class()
    ));
    body.push_str(&format!("    private {}() {{}}\n", opts.functions_class()));

    // Force every reachable generated interface to initialize so its
    // classifier → interface registration runs before user code calls
    // any wrapper method.
    if !reachable.classes.is_empty() {
        body.push_str("\n    static {\n");
        for (i, cid) in reachable.classes.iter().enumerate() {
            let java_fqn = generated_interface_fqn(model, *cid, opts);
            body.push_str(&format!(
                "        @SuppressWarnings(\"unused\") boolean __r{i} = {java_fqn}.$REGISTERED;\n"
            ));
        }
        body.push_str("    }\n");
    }

    for resolved in fns {
        emit_one_method(model, resolved, opts, &mut body)?;
    }

    body.push_str("}\n");

    let mut path = PathBuf::new();
    for seg in opts.java_root_package.split('.') {
        path.push(seg);
    }
    path.push(format!("{}.java", opts.functions_class()));

    Ok(JavaFile {
        relative_path: path,
        contents: body,
    })
}

fn emit_one_method(
    model: &PureModel,
    resolved: &ResolvedFn,
    opts: &Options,
    out: &mut String,
) -> Result<(), CodegenError> {
    let function = match model.get_element(resolved.element_id) {
        Element::Function(f) => f,
        _ => unreachable!("resolve_requested guarantees Function"),
    };

    let method_name = java_static_method_name(resolved.fqn.as_str());

    // Render parameter types and the return type up-front so any error
    // surfaces with the function attribution we want.
    let mut java_params: Vec<(String, JavaType)> = Vec::with_capacity(function.parameters.len());
    for param in function.parameters.iter() {
        let ty = render_java_type(
            model,
            &param.type_expr,
            &param.multiplicity,
            resolved.fqn.as_str(),
            TypePosition::Parameter(param.name.as_str()),
            opts,
        )?;
        java_params.push((safe_java_identifier(param.name.as_str()), ty));
    }
    let return_ty = render_java_type(
        model,
        &function.return_type,
        &function.return_multiplicity,
        resolved.fqn.as_str(),
        TypePosition::Return,
        opts,
    )?;

    out.push_str("\n    public static ");
    out.push_str(&return_ty.source);
    out.push(' ');
    out.push_str(&method_name);
    out.push('(');
    for (i, (name, ty)) in java_params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&ty.source);
        out.push(' ');
        out.push_str(name);
    }
    if !java_params.is_empty() {
        out.push_str(", ");
    }
    out.push_str("PureRustEvaluator eval) {\n");

    out.push_str("        Object __result = eval.evaluate(\"");
    out.push_str(&escape_java_string(resolved.fqn.as_str()));
    out.push('"');
    for (name, _) in java_params.iter() {
        out.push_str(", PureProxyFactory.unwrap(");
        out.push_str(name);
        out.push(')');
    }
    out.push_str(");\n");

    if return_ty.source == "void" {
        out.push_str("    }\n");
        return Ok(());
    }

    // Tell the proxy factory the declared static return type via
    // a class-literal token; for parameterized types we pass `null` and
    // an explicit cast — the factory will fall back to checking the raw
    // value and, for user types, use the declared interface from the
    // generated method signature when the runtime classifier is
    // unregistered.
    out.push_str("        return ");
    out.push_str(&format!("({}) ", return_ty.source));
    out.push_str("PureProxyFactory.wrap(__result, ");
    out.push_str(&type_token_for_return(&return_ty));
    out.push_str(", eval);\n");
    out.push_str("    }\n");

    Ok(())
}

fn type_token_for_return(ty: &JavaType) -> String {
    // For raw class types we can pass `T.class`; for parameterized types
    // (Iterable<X>, Optional<X>) we pass `null` and the wrap() runtime
    // path inspects the actual value plus its element type via reflection
    // on the call site if needed. This is good enough for v1 because the
    // factory still falls back to the declared interface for user types
    // through the static cast on the caller side.
    if ty.source.contains('<') {
        "null".to_owned()
    } else {
        format!("{}.class", ty.source)
    }
}

fn generated_interface_fqn(model: &PureModel, id: ElementId, opts: &Options) -> String {
    let segments = pure_fqn_segments(model, id);
    let leaf = segments.last().map(smol_str::SmolStr::as_str).unwrap_or("");
    let pkg_segments = pure_package_segments_of(model, id);
    let java_pkg = join_java_package(&opts.java_root_package, &pkg_segments);
    format!("{java_pkg}.{}", safe_java_identifier(leaf))
}

fn escape_java_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}
