// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Emits one Java interface per reachable user `Class`.
//!
//! Each interface:
//! - extends the generated interfaces of every Pure supertype that is also
//!   in the reachable set;
//! - declares one zero-arg method per simple property;
//! - declares one method per qualified property (parameters mirror the
//!   QP's parameter list);
//! - carries the two `$instancePointer()` / `$evaluator()` sentinel
//!   accessors (defined once on `PureRegistered`);
//! - registers itself with `PureProxyFactory` via a static initializer
//!   block so subtype-aware proxying works at runtime.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use legend_pure_parser_pure::ids::ElementId;
use legend_pure_parser_pure::model::{Element, PureModel};
use legend_pure_parser_pure::types::{Multiplicity, TypeExpr};

use crate::closure::ReachableSet;
use crate::model::{Bootstrap, CodegenError, JavaFile, Options};
use crate::naming::{
    join_java_package, pure_fqn_segments, pure_fqn_string, pure_package_segments_of,
    safe_java_identifier,
};
use crate::types::{GenericPolicy, TypePosition, render_java_type};

/// FQN of the hand-written `Any` interface every generated interface
/// extends (transitively). Substituted in for any reference to
/// `meta::pure::metamodel::type::Any` and used as the universal
/// fallback when a class has no other supertype-in-the-closure.
const HAND_WRITTEN_ANY_FQN: &str = "org.finos.legend.pure.rust.proxy.Any";

pub(crate) fn emit_class_interface(
    model: &PureModel,
    class_id: ElementId,
    reachable: &ReachableSet,
    opts: &Options,
    bootstrap: Bootstrap,
) -> Result<JavaFile, CodegenError> {
    let segments = pure_fqn_segments(model, class_id);
    let leaf = segments.last().map_or("Class", smol_str::SmolStr::as_str);
    let java_simple = safe_java_identifier(leaf);
    let pkg_segments = pure_package_segments_of(model, class_id);
    let java_package = join_java_package(&opts.java_root_package, &pkg_segments);
    let pure_fqn = pure_fqn_string(model, class_id);
    let Element::Class(class) = model.get_element(class_id) else {
        unreachable!("emit_class_interface called on non-Class element")
    };

    let mut body = String::new();
    body.push_str("// Generated by legend-pure-java-codegen — do not edit by hand.\n");
    let _ = writeln!(body, "package {java_package};\n");
    body.push_str("import org.finos.legend.pure.rust.PureRustEvaluator;\n");
    body.push_str("import org.finos.legend.pure.rust.proxy.PureProxyFactory;\n\n");

    // Build the `extends` list. Each Pure supertype either:
    //   * resolves to `meta::pure::metamodel::type::Any` → substitute
    //     the hand-written `org.finos.legend.pure.rust.proxy.Any`;
    //   * is itself a generated interface in this closure → reference
    //     its emitted FQN;
    //   * otherwise → skipped (out-of-closure platform class).
    // When the list ends up empty, default to the hand-written Any so
    // every generated interface ultimately extends it.
    let mut extends_list: Vec<String> = Vec::new();
    for super_ty in &class.super_types {
        if let TypeExpr::Named { element, .. } = super_ty {
            if bootstrap.is_any(*element) {
                extends_list.push(HAND_WRITTEN_ANY_FQN.to_owned());
                continue;
            }
            // External-binding supertype: another module already
            // emitted the parent interface. Reference its imported
            // Java FQN so this child compiles as a real subtype.
            if !opts.external_bindings.is_empty()
                && let Some(java_fqn) = opts
                    .external_bindings
                    .get(&pure_fqn_string(model, *element))
            {
                extends_list.push(java_fqn.clone());
                continue;
            }
            if reachable.contains_class(*element) {
                let segs = pure_fqn_segments(model, *element);
                let leaf2 = segs.last().map_or("", smol_str::SmolStr::as_str);
                let p = pure_package_segments_of(model, *element);
                let pkg = join_java_package(&opts.java_root_package, &p);
                extends_list.push(format!("{pkg}.{}", safe_java_identifier(leaf2)));
            }
        }
    }
    if extends_list.is_empty() {
        extends_list.push(HAND_WRITTEN_ANY_FQN.to_owned());
    }

    let _ = writeln!(
        body,
        "public interface {java_simple} extends {} {{",
        extends_list.join(", ")
    );

    // Property names declared on any in-closure supertype. Pure allows
    // a subclass to *redeclare* a property already defined on a
    // supertype (often as a no-op shadowing for documentation), but
    // emitting the redeclaration as a default method on the child
    // creates a Java diamond-inheritance conflict whenever the child
    // also extends a sibling interface that provides its own default
    // for the same name. Suppress the redeclaration on the child side
    // and inherit the supertype's default. Multiplicity narrowing /
    // type narrowing across distinct supertype declarations is handled
    // by `diamond_overrides` below — the joining `@Override default`
    // takes the intersection of all colliding multiplicities and the
    // most-specific common type.
    let supertype_property_names = collect_supertype_property_names(model, class_id, reachable);

    // Direct properties.
    for prop in &class.properties {
        if supertype_property_names.contains(prop.name.as_str()) {
            continue;
        }
        let return_ty = render_java_type(
            model,
            &prop.type_expr,
            &prop.multiplicity,
            &pure_fqn,
            TypePosition::Return,
            opts,
            GenericPolicy::AsObject,
            bootstrap,
        )?;
        let java_name = safe_java_identifier(prop.name.as_str());
        emit_property_decl(&return_ty.source, &java_name, &prop.multiplicity, &mut body);
    }

    // Qualified properties — keep abstract regardless of multiplicity.
    // The user *must* implement them since their semantics is computed,
    // not a stored value; defaulting them to empty would silently
    // pretend they returned nothing.
    for qp in &class.qualified_properties {
        let return_ty = render_java_type(
            model,
            &qp.return_type,
            &qp.return_multiplicity,
            &pure_fqn,
            TypePosition::Return,
            opts,
            GenericPolicy::AsObject,
            bootstrap,
        )?;
        let _ = write!(body, "    {} ", return_ty.source);
        body.push_str(&safe_java_identifier(qp.name.as_str()));
        body.push('(');
        for (i, param) in qp.parameters.iter().enumerate() {
            if i > 0 {
                body.push_str(", ");
            }
            let ty = render_java_type(
                model,
                &param.type_expr,
                &param.multiplicity,
                &pure_fqn,
                TypePosition::Parameter(param.name.as_str()),
                opts,
                GenericPolicy::AsObject,
                bootstrap,
            )?;
            let _ = write!(
                body,
                "{} {}",
                ty.source,
                safe_java_identifier(param.name.as_str())
            );
        }
        body.push_str(");\n");
    }

    // Association-injected properties. The model's
    // `association_properties` index registers each property on its OWN
    // declared target class; the property that's *navigable* from this
    // class is the OTHER end (`1 - prop_idx_pointing_to_self`). Mirrors
    // `crates/pure/src/infer.rs:1755`.
    for (assoc_id, prop_idx_pointing_to_self) in model.association_properties(class_id) {
        if let Element::Association(assoc) = model.get_element(*assoc_id)
            && assoc.properties.len() == 2
            && let Some(injected) = assoc.properties.get(1 - *prop_idx_pointing_to_self)
        {
            if supertype_property_names.contains(injected.name.as_str()) {
                continue;
            }
            let return_ty = render_java_type(
                model,
                &injected.type_expr,
                &injected.multiplicity,
                &pure_fqn,
                TypePosition::Return,
                opts,
                GenericPolicy::AsObject,
                bootstrap,
            )?;
            let java_name = safe_java_identifier(injected.name.as_str());
            emit_property_decl(
                &return_ty.source,
                &java_name,
                &injected.multiplicity,
                &mut body,
            );
        }
    }

    // Diamond resolution. When the supertype graph above this class
    // contains two ancestors-in-closure that each declare a property
    // with the same name, Java rejects the resulting interface because
    // it "inherits unrelated defaults" from both branches. Emit an
    // explicit `default` override here for every such property so the
    // joining interface picks one body deterministically and the
    // diamond is broken. The override re-uses the first declaration
    // we encounter; the runtime always routes through the proxy
    // factory so the body is only material to hand-written impls of
    // the interface.
    let direct_property_names = direct_property_name_set(model, class_id);
    for diamond in diamond_overrides(model, class_id, reachable, opts, bootstrap)? {
        if direct_property_names.contains(&diamond.name) {
            // Already emitted above; the supertype-name skip handled it.
            continue;
        }
        let _ = writeln!(
            body,
            "    @Override default {} {}() {{ return {}; }}",
            diamond.java_type, diamond.java_name, diamond.default_body,
        );
    }

    // Subtype-aware proxy registration. Initialising `$REGISTERED` runs
    // `__register()` once when the interface is first referenced (any
    // read of `$REGISTERED` triggers JLS §12.4.1 init).
    body.push_str("\n    /** Sentinel forcing classifier→interface registration on init. */\n");
    body.push_str("    boolean $REGISTERED = __register();\n");
    body.push_str("    /** Side-effecting initializer for {@link #$REGISTERED}. */\n");
    body.push_str("    static boolean __register() {\n");
    let _ = writeln!(
        body,
        "        PureProxyFactory.register(\"{}\", {}.class);",
        escape_java_string(&pure_fqn),
        java_simple
    );
    body.push_str("        return true;\n");
    body.push_str("    }\n");

    body.push_str("}\n");

    let mut path = PathBuf::new();
    for seg in java_package.split('.') {
        path.push(seg);
    }
    path.push(format!("{java_simple}.java"));

    Ok(JavaFile {
        relative_path: path,
        contents: body,
    })
}

/// One diamond-override emission unit, computed from the transitive
/// ancestor declarations of the class being emitted.
#[derive(Debug)]
struct DiamondOverride {
    name: String,
    java_name: String,
    java_type: String,
    default_body: String,
}

/// Property names declared **directly** by a class (own properties,
/// qualified properties, and association-injected properties) — used
/// to dedupe diamond emissions against the direct-property emission
/// loop above.
fn direct_property_name_set(model: &PureModel, class_id: ElementId) -> HashSet<String> {
    let mut names = HashSet::<String>::new();
    if let Element::Class(class) = model.get_element(class_id) {
        for prop in &class.properties {
            names.insert(prop.name.as_str().to_owned());
        }
        for qp in &class.qualified_properties {
            names.insert(qp.name.as_str().to_owned());
        }
        for (assoc_id, prop_idx_pointing_to_self) in model.association_properties(class_id) {
            if let Element::Association(assoc) = model.get_element(*assoc_id)
                && assoc.properties.len() == 2
                && let Some(injected) = assoc.properties.get(1 - *prop_idx_pointing_to_self)
            {
                names.insert(injected.name.as_str().to_owned());
            }
        }
    }
    names
}

/// For each simple property name declared by **two or more distinct**
/// ancestors-in-closure of `class_id`, return one [`DiamondOverride`]
/// describing the override emission this class needs.
///
/// **Multiplicity policy.** When the colliding declarations agree on
/// multiplicity (the typical M3 case — two ancestors with shadowed
/// copies of `name: String[1]`), that shared multiplicity flows
/// through unchanged. When they disagree (e.g. `[0..1]` on one branch,
/// `[1]` on the other), the override emits the **intersection** —
/// `max(lower)..min(upper)`. The intersection is the only multiplicity
/// that simultaneously satisfies every upstream contract; emitting a
/// looser shape would produce a default body that violates the
/// stricter parent's `[1]` requirement, and emitting a stricter shape
/// would over-constrain the optional branch. Unsatisfiable
/// intersections (lower > upper after combining) fall back to
/// [`Multiplicity::PureOne`] so the generated method stays abstract
/// at runtime — the validator's `PropertyConflict` rule already
/// rejects this configuration, so reaching the fallback means we're
/// emitting from an unvalidated or partial model.
///
/// **Type policy.** Pick the most-specific common type — if one
/// declaration's type is a subtype of every other's, that's the
/// emission type. Otherwise fall back to the first declaration; this
/// case is also rejected by the validator (`is_simple_property_override_valid`
/// requires structural type identity), so the fallback only fires
/// under the same "unvalidated model" condition as the multiplicity
/// fallback.
///
/// Qualified properties and association-injected properties are
/// included in the conflict set, but only simple-property collisions
/// produce overrides — qualified properties are abstract on every
/// emitted interface so the diamond never forms for them.
fn diamond_overrides(
    model: &PureModel,
    class_id: ElementId,
    reachable: &ReachableSet,
    opts: &Options,
    bootstrap: Bootstrap,
) -> Result<Vec<DiamondOverride>, CodegenError> {
    // Walk every ancestor-in-closure once. For each simple property
    // declaration, record (declaring-ancestor-id, prop-clone) so we
    // can later detect "same name, two distinct ancestors".
    let mut by_name: HashMap<String, Vec<(ElementId, TypeExpr, Multiplicity)>> = HashMap::new();
    let mut visited = HashSet::<ElementId>::new();
    walk_ancestors_collecting(model, class_id, reachable, &mut visited, &mut by_name);

    // Stable iteration order — sort property names alphabetically so
    // codegen output is deterministic.
    let mut sorted_names: Vec<&String> = by_name.keys().collect();
    sorted_names.sort();

    let pure_fqn = pure_fqn_string(model, class_id);
    let mut out = Vec::new();
    for name in sorted_names {
        let Some(decls) = by_name.get(name) else {
            continue;
        };
        // Diamond is signalled by two or more distinct declaring ancestors.
        let distinct: HashSet<ElementId> = decls.iter().map(|(id, _, _)| *id).collect();
        if distinct.len() < 2 {
            continue;
        }
        // Intersect multiplicities across every distinct ancestor
        // declaration; narrow types to the most-specific common one.
        // Both helpers are deterministic and produce semantically
        // sound emissions even when the input declarations disagree.
        let intersected_mult = intersect_multiplicities(decls.iter().map(|(_, _, m)| m));
        let chosen_ty = most_specific_type(model, decls);
        let return_ty = render_java_type(
            model,
            chosen_ty,
            &intersected_mult,
            &pure_fqn,
            TypePosition::Return,
            opts,
            GenericPolicy::AsObject,
            bootstrap,
        )?;
        let java_name = safe_java_identifier(name);
        let default_body = match default_body_for(&intersected_mult) {
            Some(body) => body.to_owned(),
            // [1] mults can't easily resolve a diamond from the joining
            // class — fall back to throwing at runtime so the generated
            // code still compiles. The proxy invocation handler routes
            // around this body in practice.
            None => {
                "java.util.Objects.requireNonNull(null, \"abstract diamond property\")".to_owned()
            }
        };
        out.push(DiamondOverride {
            name: name.clone(),
            java_name,
            java_type: return_ty.source,
            default_body,
        });
    }
    Ok(out)
}

/// Intersect a sequence of multiplicities into the narrowest shape
/// that satisfies every input — `max(lower)..min(upper)`. Used by
/// [`diamond_overrides`] to pick a single multiplicity that's sound
/// under all colliding ancestor declarations.
///
/// Returns [`Multiplicity::PureOne`] when the intersection is empty
/// (`lower > upper`) — the validator's `PropertyConflict` rule rejects
/// that case, so the fallback only matters for emissions from
/// partially-validated models. Otherwise reconstructs the canonical
/// shape: `PureOne` for `1..1`, `ZeroOrOne` for `0..1`, `OneOrMany`
/// for `1..*`, `ZeroOrMany` for `0..*`, or `Range` for the rest.
fn intersect_multiplicities<'a>(mults: impl Iterator<Item = &'a Multiplicity>) -> Multiplicity {
    let (mut lo, mut hi) = (0u32, u32::MAX);
    let mut saw_any = false;
    for m in mults {
        saw_any = true;
        let (l, h) = mult_bounds_local(m);
        if l > lo {
            lo = l;
        }
        if h < hi {
            hi = h;
        }
    }
    if !saw_any || lo > hi {
        return Multiplicity::PureOne;
    }
    match (lo, hi) {
        (1, 1) => Multiplicity::PureOne,
        (0, 1) => Multiplicity::ZeroOrOne,
        (1, u32::MAX) => Multiplicity::OneOrMany,
        (0, u32::MAX) => Multiplicity::ZeroOrMany,
        (lower, hi_v) => Multiplicity::Range {
            lower,
            upper: if hi_v == u32::MAX { None } else { Some(hi_v) },
        },
    }
}

/// Local copy of `resolve::mult_bounds` — the pure crate exports the
/// helper as `pub(crate)`, not `pub`, so we mirror it here rather than
/// widen its visibility just for codegen.
fn mult_bounds_local(m: &Multiplicity) -> (u32, u32) {
    match m {
        Multiplicity::PureOne => (1, 1),
        Multiplicity::ZeroOrOne => (0, 1),
        Multiplicity::OneOrMany => (1, u32::MAX),
        Multiplicity::Range { lower, upper } => (*lower, upper.unwrap_or(u32::MAX)),
        Multiplicity::ZeroOrMany | Multiplicity::Variable(_) => (0, u32::MAX),
    }
}

/// Pick the most-specific type among `decls`: the one whose `TypeExpr`
/// is a subtype of every other declaration's. Falls back to the first
/// declaration's type when no such common subtype exists.
///
/// Non-`Named` type expressions (`Generic`, `FunctionType`) are
/// treated permissively — they're type holes that any concrete type
/// can flow into, so a `Named` declaration counts as a subtype of
/// any non-`Named` peer.
fn most_specific_type<'a>(
    model: &PureModel,
    decls: &'a [(ElementId, TypeExpr, Multiplicity)],
) -> &'a TypeExpr {
    use legend_pure_parser_pure::resolve::is_subtype;
    for (_, candidate_ty, _) in decls {
        let TypeExpr::Named {
            element: candidate_eid,
            ..
        } = candidate_ty
        else {
            continue;
        };
        let is_specific = decls.iter().all(|(_, other_ty, _)| match other_ty {
            TypeExpr::Named {
                element: other_eid, ..
            } => *candidate_eid == *other_eid || is_subtype(*candidate_eid, *other_eid, model),
            _ => true,
        });
        if is_specific {
            return candidate_ty;
        }
    }
    &decls[0].1
}

fn walk_ancestors_collecting(
    model: &PureModel,
    from_class: ElementId,
    reachable: &ReachableSet,
    visited: &mut HashSet<ElementId>,
    by_name: &mut HashMap<String, Vec<(ElementId, TypeExpr, Multiplicity)>>,
) {
    let Element::Class(class) = model.get_element(from_class) else {
        return;
    };
    for super_ty in &class.super_types {
        if let TypeExpr::Named { element, .. } = super_ty
            && reachable.contains_class(*element)
            && visited.insert(*element)
        {
            if let Element::Class(ancestor) = model.get_element(*element) {
                for prop in &ancestor.properties {
                    by_name
                        .entry(prop.name.as_str().to_owned())
                        .or_default()
                        .push((*element, prop.type_expr.clone(), prop.multiplicity.clone()));
                }
                // Association-injected props on the ancestor end up
                // navigable from any subtype, same diamond risk.
                for (assoc_id, prop_idx_pointing_to_self) in model.association_properties(*element)
                {
                    if let Element::Association(assoc) = model.get_element(*assoc_id)
                        && assoc.properties.len() == 2
                        && let Some(injected) = assoc.properties.get(1 - *prop_idx_pointing_to_self)
                    {
                        by_name
                            .entry(injected.name.as_str().to_owned())
                            .or_default()
                            .push((
                                *element,
                                injected.type_expr.clone(),
                                injected.multiplicity.clone(),
                            ));
                    }
                }
            }
            walk_ancestors_collecting(model, *element, reachable, visited, by_name);
        }
    }
}

/// Walk the transitive supertype chain of `class_id` (restricted to
/// classes also in `reachable`) and collect the set of property names
/// — direct, qualified, and association-injected — that any such
/// supertype declares. Used to suppress redeclarations on the child
/// side that would otherwise cause Java diamond-inheritance conflicts
/// against a sibling parent's default body.
fn collect_supertype_property_names(
    model: &PureModel,
    class_id: ElementId,
    reachable: &ReachableSet,
) -> HashSet<String> {
    let mut names = HashSet::<String>::new();
    let mut visited = HashSet::<ElementId>::new();
    let Element::Class(class) = model.get_element(class_id) else {
        return names;
    };
    for super_ty in &class.super_types {
        if let TypeExpr::Named { element, .. } = super_ty
            && reachable.contains_class(*element)
        {
            collect_property_names_recursive(model, *element, reachable, &mut names, &mut visited);
        }
    }
    names
}

fn collect_property_names_recursive(
    model: &PureModel,
    class_id: ElementId,
    reachable: &ReachableSet,
    names: &mut HashSet<String>,
    visited: &mut HashSet<ElementId>,
) {
    if !visited.insert(class_id) {
        return;
    }
    let Element::Class(class) = model.get_element(class_id) else {
        return;
    };
    for prop in &class.properties {
        names.insert(prop.name.as_str().to_owned());
    }
    for qp in &class.qualified_properties {
        names.insert(qp.name.as_str().to_owned());
    }
    for (assoc_id, prop_idx_pointing_to_self) in model.association_properties(class_id) {
        if let Element::Association(assoc) = model.get_element(*assoc_id)
            && assoc.properties.len() == 2
            && let Some(injected) = assoc.properties.get(1 - *prop_idx_pointing_to_self)
        {
            names.insert(injected.name.as_str().to_owned());
        }
    }
    // Recurse into further supertypes.
    for super_ty in &class.super_types {
        if let TypeExpr::Named { element, .. } = super_ty
            && reachable.contains_class(*element)
        {
            collect_property_names_recursive(model, *element, reachable, names, visited);
        }
    }
}

/// Emit one property declaration (simple property or
/// association-injected). Properties with `[1]` multiplicity stay
/// abstract — the user must supply a value. Properties with `[0..1]`
/// or any "many" multiplicity get a default body returning empty, so
/// hand-written impls of the interface only need to override the
/// fields they care about.
///
/// Generated proxies always route through the invocation handler
/// (which goes native), so the default body is never invoked for a
/// proxy — it only matters for user-written `implements` classes.
fn emit_property_decl(java_type: &str, java_name: &str, mult: &Multiplicity, out: &mut String) {
    match default_body_for(mult) {
        None => {
            let _ = writeln!(out, "    {java_type} {java_name}();");
        }
        Some(body) => {
            let _ = writeln!(
                out,
                "    default {java_type} {java_name}() {{ return {body}; }}"
            );
        }
    }
}

/// Return the Java expression to use as the default-method body for a
/// given Pure multiplicity, or `None` when the property must remain
/// abstract.
fn default_body_for(mult: &Multiplicity) -> Option<&'static str> {
    match mult {
        Multiplicity::PureOne => None,
        Multiplicity::ZeroOrOne => Some("java.util.Optional.empty()"),
        Multiplicity::ZeroOrMany | Multiplicity::OneOrMany | Multiplicity::Variable(_) => {
            Some("java.util.Collections.emptyList()")
        }
        Multiplicity::Range { lower, upper } => {
            if *lower == 1 && *upper == Some(1) {
                None
            } else {
                Some("java.util.Collections.emptyList()")
            }
        }
    }
}

fn escape_java_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}
