// Copyright 2026 Goldman Sachs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Emits one Java interface per reachable user `Class`.
//!
//! Each interface:
//! - extends the generated interfaces of every Pure supertype that is also
//!   in the reachable set;
//! - declares one zero-arg method per simple property;
//! - declares one method per qualified property (parameters mirror the
//!   QP's parameter list);
//! - carries the two `$instancePointer()` / `$evaluator()` sentinel
//!   accessors (defined once on `PureRegistered`);
//! - registers itself with `PureProxyFactory` via a static initializer
//!   block so subtype-aware proxying works at runtime.

use std::path::PathBuf;

use legend_pure_parser_pure::ids::ElementId;
use legend_pure_parser_pure::model::{Element, PureModel};
use legend_pure_parser_pure::types::TypeExpr;

use crate::closure::ReachableSet;
use crate::model::{CodegenError, JavaFile, Options};
use crate::naming::{
    join_java_package, pure_fqn_segments, pure_fqn_string, pure_package_segments_of,
    safe_java_identifier,
};
use crate::types::{GenericPolicy, TypePosition, render_java_type};

pub(crate) fn emit_class_interface(
    model: &PureModel,
    class_id: ElementId,
    reachable: &ReachableSet,
    opts: &Options,
) -> Result<JavaFile, CodegenError> {
    let segments = pure_fqn_segments(model, class_id);
    let leaf = segments
        .last()
        .map(smol_str::SmolStr::as_str)
        .unwrap_or("Class");
    let java_simple = safe_java_identifier(leaf);
    let pkg_segments = pure_package_segments_of(model, class_id);
    let java_package = join_java_package(&opts.java_root_package, &pkg_segments);
    let pure_fqn = pure_fqn_string(model, class_id);
    let class = match model.get_element(class_id) {
        Element::Class(c) => c,
        _ => unreachable!("emit_class_interface called on non-Class element"),
    };

    let mut body = String::new();
    body.push_str("// Generated by legend-pure-java-codegen — do not edit by hand.\n");
    body.push_str(&format!("package {java_package};\n\n"));
    body.push_str("import org.finos.legend.pure.rust.PureRustEvaluator;\n");
    body.push_str("import org.finos.legend.pure.rust.proxy.PureRegistered;\n");
    body.push_str("import org.finos.legend.pure.rust.proxy.PureProxyFactory;\n\n");

    // Build the `extends` list — every supertype that is itself a generated
    // interface in this batch. Falls back to `PureRegistered` when no
    // generated supertype exists.
    let mut extends_list: Vec<String> = Vec::new();
    for super_ty in &class.super_types {
        if let TypeExpr::Named { element, .. } = super_ty
            && reachable.contains_class(*element)
        {
            let s = pure_fqn_segments(model, *element);
            let leaf2 = s.last().map(smol_str::SmolStr::as_str).unwrap_or("");
            let p = pure_package_segments_of(model, *element);
            let pkg = join_java_package(&opts.java_root_package, &p);
            extends_list.push(format!("{pkg}.{}", safe_java_identifier(leaf2)));
        }
    }
    if extends_list.is_empty() {
        extends_list.push("PureRegistered".to_owned());
    }

    body.push_str(&format!(
        "public interface {java_simple} extends {} {{\n",
        extends_list.join(", ")
    ));

    // Direct properties.
    for prop in &class.properties {
        let return_ty = render_java_type(
            model,
            &prop.type_expr,
            &prop.multiplicity,
            &pure_fqn,
            TypePosition::Return,
            opts,
            GenericPolicy::AsObject,
        )?;
        body.push_str(&format!(
            "    {} {}();\n",
            return_ty.source,
            safe_java_identifier(prop.name.as_str())
        ));
    }

    // Qualified properties.
    for qp in &class.qualified_properties {
        let return_ty = render_java_type(
            model,
            &qp.return_type,
            &qp.return_multiplicity,
            &pure_fqn,
            TypePosition::Return,
            opts,
            GenericPolicy::AsObject,
        )?;
        body.push_str(&format!("    {} ", return_ty.source));
        body.push_str(&safe_java_identifier(qp.name.as_str()));
        body.push('(');
        for (i, param) in qp.parameters.iter().enumerate() {
            if i > 0 {
                body.push_str(", ");
            }
            let ty = render_java_type(
                model,
                &param.type_expr,
                &param.multiplicity,
                &pure_fqn,
                TypePosition::Parameter(param.name.as_str()),
                opts,
                GenericPolicy::AsObject,
            )?;
            body.push_str(&format!(
                "{} {}",
                ty.source,
                safe_java_identifier(param.name.as_str())
            ));
        }
        body.push_str(");\n");
    }

    // Association-injected properties. The model's
    // `association_properties` index registers each property on its OWN
    // declared target class; the property that's *navigable* from this
    // class is the OTHER end (`1 - prop_idx_pointing_to_self`). Mirrors
    // `crates/pure/src/infer.rs:1755`.
    for (assoc_id, prop_idx_pointing_to_self) in model.association_properties(class_id) {
        if let Element::Association(assoc) = model.get_element(*assoc_id)
            && assoc.properties.len() == 2
            && let Some(injected) = assoc.properties.get(1 - *prop_idx_pointing_to_self)
        {
            let return_ty = render_java_type(
                model,
                &injected.type_expr,
                &injected.multiplicity,
                &pure_fqn,
                TypePosition::Return,
                opts,
                GenericPolicy::AsObject,
            )?;
            body.push_str(&format!(
                "    {} {}();\n",
                return_ty.source,
                safe_java_identifier(injected.name.as_str())
            ));
        }
    }

    // Subtype-aware proxy registration. Initialising `$REGISTERED` runs
    // `__register()` once when the interface is first referenced (any
    // read of `$REGISTERED` triggers JLS §12.4.1 init).
    body.push_str("\n    /** Sentinel forcing classifier→interface registration on init. */\n");
    body.push_str("    boolean $REGISTERED = __register();\n");
    body.push_str("    /** Side-effecting initializer for {@link #$REGISTERED}. */\n");
    body.push_str("    static boolean __register() {\n");
    body.push_str(&format!(
        "        PureProxyFactory.register(\"{}\", {}.class);\n",
        escape_java_string(&pure_fqn),
        java_simple
    ));
    body.push_str("        return true;\n");
    body.push_str("    }\n");

    body.push_str("}\n");

    let mut path = PathBuf::new();
    for seg in java_package.split('.') {
        path.push(seg);
    }
    path.push(format!("{java_simple}.java"));

    Ok(JavaFile {
        relative_path: path,
        contents: body,
    })
}

fn escape_java_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}
