[package]
name = "legend-pure-core-platform"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
legend-pure-parser-parser = { path = "../parser" }
legend-pure-parser-ast = { path = "../ast" }
legend-pure-parser-pure = { path = "../pure" }
legend-pure-runtime = { path = "../runtime" }
smol_str = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
walkdir = { workspace = true }
